name: Package and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
    release: 
      runs-on: windows-latest
      if: startsWith(github.ref, 'refs/tags/')
      steps:
        - uses: actions/checkout@v2

        - name: Minebbs-Auto-Release
          uses: HuoHuas001/Minebbs-Auto-Release@v1.0.6
          with: 
            resources: '1'
            token: ${{ secrets.MINEBBSKEY }}
            title: ${{ github.ref_name }}
            new_version: ${{ github.ref_name }}
            description_file: './CHANGELOG.md'
            file_url: 'https://github.com/HuoHuas001/Minebbs-Auto-Release/releases/latest'